# Generated by Django 5.1 on 2024-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0004_article_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-is_top_pick', 'name']},
        ),
        migrations.AddField(
            model_name='software',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
