# Generated by Django 5.1 on 2024-09-16 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0006_software_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('excerpt', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('presentation_sans_gras', models.TextField()),
                ('date_en_texte', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet_digital.newscategory')),
            ],
        ),
    ]
