# Generated by Django 5.1 on 2024-09-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0009_remove_news_date_en_texte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='software_category',
        ),
        migrations.AddField(
            model_name='news',
            name='software_category',
            field=models.ManyToManyField(related_name='categories_news_link', to='cabinet_digital.softwarecategory'),
        ),
    ]
