# Generated by Django 5.1.1 on 2024-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0013_softwarecategory_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
