# Generated by Django 5.1.1 on 2024-09-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0016_alter_software_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='softwarecategory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='softwarecategory',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
