# Generated by Django 5.1 on 2024-10-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0030_remove_software_editeur_software_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
