# Generated by Django 5.1 on 2024-10-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0032_softwarecategory_softwares_alter_software_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles_categories_link', to='cabinet_digital.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles_categories_link', to='cabinet_digital.softwarecategory'),
        ),
        migrations.AlterField(
            model_name='softwarecategory',
            name='softwares',
            field=models.ManyToManyField(blank=True, related_name='categories_softwares_link', to='cabinet_digital.software'),
        ),
    ]
