# Generated by Django 5.1 on 2024-10-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0034_cible_remove_softwarecategory_articles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cible',
            new_name='Metier',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='cible',
            new_name='metier',
        ),
        migrations.RenameField(
            model_name='softwarecategory',
            old_name='cible',
            new_name='metier',
        ),
    ]
