# Generated by Django 5.1 on 2024-10-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0037_softwarecategory_is_published_alter_software_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Actualites',
        ),
    ]
