# Generated by Django 5.1 on 2024-11-09 22:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0041_remove_actualites_icon_softwarecategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarecategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
