# Generated by Django 5.1 on 2024-12-08 21:35

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cabinet_digital",
            "0046_software_preview_gif_tag_slug_alter_tag_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="description",
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name="softwarecategory",
            name="description",
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
