# Generated by Django 5.1 on 2025-01-06 21:22

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0046_software_preview_gif_tag_slug_alter_tag_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('excerpt', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ai/logos/')),
                ('website', models.URLField()),
                ('pricing', tinymce.models.HTMLField()),
                ('features', tinymce.models.HTMLField()),
                ('use_cases', tinymce.models.HTMLField()),
                ('pros', tinymce.models.HTMLField()),
                ('cons', tinymce.models.HTMLField()),
                ('is_published', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='cabinet_digital.tag')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('excerpt', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ai/tools/')),
                ('website', models.URLField()),
                ('pricing', tinymce.models.HTMLField()),
                ('features', tinymce.models.HTMLField()),
                ('use_cases', tinymce.models.HTMLField()),
                ('is_published', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ai_models', models.ManyToManyField(blank=True, to='cabinet_digital.aimodel')),
                ('tags', models.ManyToManyField(blank=True, to='cabinet_digital.tag')),
            ],
            options={
                'verbose_name': 'AI Tool',
                'verbose_name_plural': 'AI Tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('excerpt', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai/articles/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='cabinet_digital.tag')),
                ('ai_models', models.ManyToManyField(blank=True, to='cabinet_digital.aimodel')),
                ('tools', models.ManyToManyField(blank=True, to='cabinet_digital.aitool')),
            ],
            options={
                'verbose_name': 'AI Article',
                'verbose_name_plural': 'AI Articles',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='AITutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('excerpt', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai/tutorials/')),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ai_models', models.ManyToManyField(blank=True, to='cabinet_digital.aimodel')),
                ('tags', models.ManyToManyField(blank=True, to='cabinet_digital.tag')),
                ('tools', models.ManyToManyField(blank=True, to='cabinet_digital.aitool')),
            ],
            options={
                'verbose_name': 'AI Tutorial',
                'verbose_name_plural': 'AI Tutorials',
                'ordering': ['-pub_date'],
            },
        ),
    ]
