# Generated by Django 5.1 on 2025-01-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0050_remove_aimodel_excerpt_aimodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='pros',
            field=models.TextField(blank=True),
        ),
    ]
