# Generated by Django 5.1 on 2025-01-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0054_model_remove_aitool_ai_models_remove_aitool_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='ModelAI',
        ),
    ]
