# Generated by Django 5.1 on 2025-01-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0055_rename_model_modelai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelAI',
        ),
    ]
