# Generated by Django 5.1 on 2024-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Software Categories',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('editeur', models.CharField(max_length=100)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('site', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('category', models.ManyToManyField(related_name='categories_softwares_link', to='cabinet_digital.softwarecategory')),
            ],
        ),
    ]
