# Generated by Django 5.1 on 2024-09-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
