# Generated by Django 5.2 on 2025-07-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0002_contactintegrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integrateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='cabinet_digital.integrator'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='modules',
            field=models.ManyToManyField(blank=True, db_table='integrations_integration_modules', help_text='Modules comptables concernés par cette intégration', to='cabinet_digital.module', verbose_name='Modules concernés'),
        ),
        migrations.AlterModelTable(
            name='contactintegrateur',
            table='integrations_contactintegrateur',
        ),
        migrations.AlterModelTable(
            name='integration',
            table='integrations_integration',
        ),
        migrations.AlterModelTable(
            name='module',
            table='integrations_module',
        ),
        migrations.AlterModelTable(
            name='typeintegration',
            table='integrations_typeintegration',
        ),
        migrations.DeleteModel(
            name='Integrateur',
        ),
    ]
