# Generated by Django 5.1 on 2024-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(default='introo'),
            preserve_default=False,
        ),
    ]
