# Generated by Django 5.1 on 2024-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0005_alter_software_options_software_is_top_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
