# Generated by Django 5.1 on 2024-09-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0007_newscategory_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='software_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet_digital.softwarecategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
