# Generated by Django 5.1 on 2024-09-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0008_remove_news_category_news_software_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_en_texte',
        ),
        migrations.RemoveField(
            model_name='news',
            name='presentation_sans_gras',
        ),
    ]
