# Generated by Django 5.1 on 2024-09-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0010_remove_news_software_category_news_software_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='software_category',
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(related_name='news', to='cabinet_digital.softwarecategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
