# Generated by Django 5.1.1 on 2024-09-22 16:56

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0012_news_image_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='softwarecategory',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
