# Generated by Django 5.1.1 on 2024-09-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0014_software_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='view_count',
            new_name='unique_views',
        ),
    ]
