# Generated by Django 5.1.1 on 2024-09-28 10:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0015_rename_view_count_software_unique_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='softwarecategory',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
