# Generated by Django 5.1.1 on 2024-09-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0017_software_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='last_modified',
        ),
    ]
