# Generated by Django 5.1.1 on 2024-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0018_remove_software_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='seo_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='softwarecategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
