# Generated by Django 5.1.1 on 2024-09-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0021_remove_software_viewers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='view_count',
        ),
        migrations.AddField(
            model_name='software',
            name='unique_views',
            field=models.IntegerField(default=0),
        ),
    ]
