# Generated by Django 5.1 on 2024-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0022_remove_software_view_count_software_unique_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='cabinet_digital.softwarecategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(max_length=500),
        ),
    ]
