# Generated by Django 5.1 on 2024-10-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0029_remove_softwarecategory_excerpt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='editeur',
        ),
        migrations.AddField(
            model_name='software',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
