# Generated by Django 5.1 on 2024-10-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0031_alter_software_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='softwares',
            field=models.ManyToManyField(blank=True, related_name='categories', to='cabinet_digital.software'),
        ),
        migrations.AlterField(
            model_name='software',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
