# Generated by Django 5.1 on 2024-10-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0033_softwarecategory_articles_alter_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='softwarecategory',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='softwarecategory',
            name='softwares',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='categories_articles_link', to='cabinet_digital.softwarecategory'),
        ),
        migrations.AddField(
            model_name='software',
            name='cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet_digital.cible'),
        ),
        migrations.AddField(
            model_name='softwarecategory',
            name='cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet_digital.cible'),
        ),
    ]
