# Generated by Django 5.1 on 2024-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0035_rename_cible_metier_rename_cible_software_metier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cabinet_digital.tag'),
        ),
    ]
