# Generated by Django 5.1 on 2024-10-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0036_remove_article_category_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='video',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
