# Generated by Django 5.1 on 2024-10-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0038_rename_news_actualites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualites',
            options={'verbose_name_plural': 'Actualites'},
        ),
        migrations.RenameField(
            model_name='actualites',
            old_name='date',
            new_name='pub_date',
        ),
    ]
