# Generated by Django 5.1 on 2024-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0039_alter_actualites_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualites',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
