# Generated by Django 5.1 on 2024-11-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0040_actualites_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualites',
            name='icon',
        ),
        migrations.AddField(
            model_name='softwarecategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
