# Generated by Django 5.1 on 2024-11-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0042_alter_softwarecategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet_digital.software')),
            ],
            options={
                'verbose_name_plural': 'Views History',
                'unique_together': {('software', 'date')},
            },
        ),
    ]
