# Generated by Django 5.1 on 2024-11-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0042_alter_softwarecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
