# Generated by Django 5.1 on 2024-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0043_softwarecategory_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
