# Generated by Django 5.1 on 2024-11-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0043_viewshistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewshistory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Views History'},
        ),
        migrations.AlterField(
            model_name='viewshistory',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_history', to='cabinet_digital.software'),
        ),
        migrations.AlterField(
            model_name='viewshistory',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
