# Generated by Django 5.1 on 2024-11-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0044_software_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarecategory',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
