# Generated by Django 5.1 on 2025-01-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0047_aimodel_aitool_aiarticle_aitutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='tags',
        ),
    ]
