# Generated by Django 5.1 on 2025-01-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0048_remove_aimodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='use_cases',
        ),
    ]
