# Generated by Django 5.1 on 2025-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0049_remove_aimodel_features_remove_aimodel_use_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
