# Generated by Django 5.1 on 2025-01-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0051_alter_aimodel_cons_alter_aimodel_pros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=models.TextField(),
        ),
    ]
