# Generated by Django 5.1 on 2025-01-20 22:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0052_alter_aimodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitool',
            name='features',
        ),
        migrations.AlterField(
            model_name='actualites',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='actualites',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='aiarticle',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='pricing',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='pricing',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='use_cases',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.DeleteModel(
            name='AITutorial',
        ),
    ]
