# Generated by Django 5.1 on 2025-01-24 22:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0053_remove_aitool_features_alter_actualites_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='models/logos')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aitool',
            name='ai_models',
        ),
        migrations.RemoveField(
            model_name='aitool',
            name='tags',
        ),
        migrations.AlterField(
            model_name='actualites',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actualites',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='AIArticle',
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
        migrations.DeleteModel(
            name='AITool',
        ),
    ]
