# Generated by Django 5.1 on 2025-01-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0047_alter_software_description_and_more'),
        ('cabinet_digital', '0056_delete_modelai'),
    ]

    operations = [
    ]
