# Generated by Django 5.1 on 2025-01-26 20:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0057_merge_20250126_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('is_published', models.BooleanField(default=False)),
                ('site', models.URLField(blank=True)),
                ('is_top_pick', models.BooleanField(default=False)),
                ('unique_views', models.IntegerField(default=0)),
                ('test_prompt', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_top_pick', models.BooleanField(default=False)),
                ('unique_views', models.IntegerField(default=0)),
                ('site', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Outil IA',
                'verbose_name_plural': 'Outils IA',
            },
        ),
        migrations.CreateModel(
            name='AIArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Article IA',
                'verbose_name_plural': 'Articles IA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cabinet_digital.article',),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='softwarecategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
