# Generated by Django 5.1 on 2025-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0059_delete_aiarticle_aiarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='test_prompt',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
