# Generated by Django 5.1 on 2025-01-27 20:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0060_remove_aimodel_test_prompt_aimodel_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='aitool',
            name='category',
            field=models.ManyToManyField(blank=True, to='cabinet_digital.aitoolcategory'),
        ),
    ]
