# Generated by Django 5.1 on 2025-02-02 18:20

from django.db import migrations

def migrate_providers_forward(apps, schema_editor):
    AIModel = apps.get_model('cabinet_digital', 'AIModel')
    ProviderAI = apps.get_model('cabinet_digital', 'ProviderAI')
    
    # Récupérer tous les noms de providers uniques des modèles existants
    existing_providers = set(AIModel.objects.values_list('provider', flat=True).distinct())
    
    # Créer les providers
    provider_mapping = {}
    for provider_name in existing_providers:
        if provider_name:  # Ignorer les valeurs None
            provider = ProviderAI.objects.create(
                name=provider_name,
                slug=provider_name.lower().replace(' ', '-'),
                is_published=True
            )
            provider_mapping[provider_name] = provider
    
    # Mettre à jour les références dans AIModel
    for model in AIModel.objects.all():
        if model.provider and model.provider in provider_mapping:
            model.provider_id = provider_mapping[model.provider].id
            model.save()

def migrate_providers_backward(apps, schema_editor):
    AIModel = apps.get_model('cabinet_digital', 'AIModel')
    ProviderAI = apps.get_model('cabinet_digital', 'ProviderAI')
    
    # Restaurer les noms de providers comme chaînes de caractères
    for model in AIModel.objects.all():
        if model.provider_id:
            provider = ProviderAI.objects.get(id=model.provider_id)
            model.provider = provider.name
            model.save()
    
    # Supprimer tous les providers
    ProviderAI.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0062_providerai_aitool_provider_alter_aimodel_provider'),
    ]

    operations = [
        migrations.RunPython(migrate_providers_forward, migrate_providers_backward),
    ]
