# Generated by Django 5.1 on 2025-02-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0064_aimodel_provider_name_temp'),
    ]

    operations = [
    ]
