# Generated by Django 5.1 on 2025-02-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0067_migrate_provider_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='provider_name_temp',
            new_name='provider_name',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='provider_old',
        ),
    ]
