# Generated by Django 5.1 on 2025-02-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0068_rename_provider_name_temp_aimodel_provider_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='provider_name',
        ),
    ]
