# Generated by Django 5.1 on 2025-02-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0069_remove_aimodel_provider_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'verbose_name': 'IA - Modèle', 'verbose_name_plural': 'IA - Modèles'},
        ),
    ]
