# Generated by Django 5.1 on 2025-02-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0071_alter_actualites_options_alter_aiarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitoolcategory',
            options={'verbose_name': 'IA - Catégories', 'verbose_name_plural': 'IA - Catégories'},
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={'verbose_name': 'Logiciels - Métiers', 'verbose_name_plural': 'Logiciels - Métiers'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['-is_top_pick', 'name'], 'verbose_name': 'Logiciel - Liste', 'verbose_name_plural': 'Logiciels - Liste'},
        ),
        migrations.AlterModelOptions(
            name='softwarecategory',
            options={'verbose_name': 'Logiciels - Catégories', 'verbose_name_plural': 'Logiciels - Catégories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Logiciels - Tags', 'verbose_name_plural': 'Logiciels - Tags'},
        ),
        migrations.AddField(
            model_name='aiarticle',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aiarticle',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aitool',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
