# Generated by Django 5.1 on 2025-02-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0072_alter_aitoolcategory_options_alter_metier_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitool',
            name='tags',
        ),
    ]
