# Generated by Django 5.1 on 2025-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0073_remove_aitool_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
