# Generated by Django 5.1 on 2025-02-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0074_aimodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='metier',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Description optimisée pour le référencement (160 caractères max)', max_length=160),
        ),
        migrations.AddField(
            model_name='metier',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Titre optimisé pour le référencement (60 caractères max)', max_length=60),
        ),
    ]
