# Generated by Django 5.1.1 on 2025-03-20 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0075_metier_seo_description_metier_seo_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 - Très mauvais'), (2, '2 - Mauvais'), (3, '3 - Moyen'), (4, '4 - Bon'), (5, '5 - Excellent')])),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('rejected', 'Rejeté'), ('published', 'Publié')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.TextField(blank=True, help_text="Raison du rejet (visible uniquement par l'utilisateur)", null=True)),
                ('publish_date', models.DateTimeField(blank=True, help_text='Date de publication', null=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cabinet_digital.software')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-publish_date', '-created_at'],
                'unique_together': {('user', 'software')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('order', models.IntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cabinet_digital.review')),
            ],
            options={
                'verbose_name': "Image d'avis",
                'verbose_name_plural': "Images d'avis",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cabinet_digital.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Vote d'avis",
                'verbose_name_plural': "Votes d'avis",
                'unique_together': {('user', 'review')},
            },
        ),
    ]
