# Generated by Django 5.1.1 on 2025-03-22 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_digital', '0076_review_reviewimage_userprofile_reviewvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSoftwareCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('share_token', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_software', models.ManyToManyField(blank=True, related_name='in_interested_collections', to='cabinet_digital.software')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_collections', to=settings.AUTH_USER_MODEL)),
                ('using_software', models.ManyToManyField(blank=True, related_name='in_using_collections', to='cabinet_digital.software')),
            ],
            options={
                'verbose_name': 'Collection de logiciels',
                'verbose_name_plural': 'Collections de logiciels',
            },
        ),
        migrations.CreateModel(
            name='UserSoftwareSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('using', 'Logiciels utilisés'), ('interested', 'Logiciels souhaités')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='cabinet_digital.software')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sélection de logiciel',
                'verbose_name_plural': 'Sélections de logiciels',
                'unique_together': {('user', 'software', 'selection_type')},
            },
        ),
    ]
